import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const P=[['sun','太阳','SUN',2.55,0,0,.08,0xffb52e],['mercury','水星','MERCURY',.34,4.2,1.6,.025,0x9c9990],['venus','金星','VENUS',.56,6.2,1.18,-.018,0xd5a16a],['earth','地球','EARTH',.59,8.5,1,.65,0x347cc7],['mars','火星','MARS',.44,11,.8,.62,0xb84f35],['jupiter','木星','JUPITER',1.38,15,.43,1.35,0xc48b60],['saturn','土星','SATURN',1.15,20,.32,1.12,0xd8b77e],['uranus','天王星','URANUS',.78,24.5,.23,-.72,0x79cbd1],['neptune','海王星','NEPTUNE',.76,29,.18,.88,0x356bd2],['pluto','冥王星','PLUTO',.25,34,.12,.35,0xa99c92]].map(x=>({id:x[0],name:x[1],latin:x[2],size:x[3],distance:x[4],orbit:x[5],rot:x[6],color:x[7],tag:x[1],desc:'太阳系天体',facts:[['直径','—'],['公转','—']]}));
const D={sun:['太阳系中心恒星','1,392,700 km'],mercury:['最小的行星','87.97 天'],venus:['最热的行星','224.7 天'],earth:['蓝色家园','365.25 天'],mars:['红色星球','687 天'],jupiter:['太阳系最大行星','11.86 年'],saturn:['壮丽光环','29.45 年'],uranus:['横躺着自转','84 年'],neptune:['最外侧八大行星','164.8 年'],pluto:['柯伊伯带矮行星','248 年']};
P.forEach(p=>{p.tag=D[p.id][0];p.facts=[['类型',p.id==='pluto'?'矮行星':p.id==='sun'?'恒星':'行星'],['公转',D[p.id][1]]]});
const BASE='https://raw.githubusercontent.com/Vivekkk-1/Galaticvisions/master/GLB/';
const URLS={sun:'Sun.glb',mercury:'Mercury.glb',venus:'Venus.glb',mars:'Mars.glb',jupiter:'Jupiter.glb',saturn:'Saturn.glb',uranus:'Uranus.glb',neptune:'Neptune.glb',pluto:'Pluto_1_2374.glb'};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x01030a);
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.03,1600);camera.position.set(30,18,38);
const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#stage'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=.4;controls.maxDistance=180;controls.target.set(8,0,0);
scene.add(new THREE.AmbientLight(0x6d7890,.22));scene.add(new THREE.PointLight(0xffd08a,520,220,1.3));
const sg=new THREE.BufferGeometry(),sp=[];for(let i=0;i<10000;i++){const r=120+Math.random()*450,a=Math.random()*6.283,b=Math.acos(2*Math.random()-1);sp.push(r*Math.sin(b)*Math.cos(a),r*Math.cos(b),r*Math.sin(b)*Math.sin(a));}sg.setAttribute('position',new THREE.Float32BufferAttribute(sp,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.11,transparent:true,opacity:.8})));
const root=new THREE.Group();scene.add(root);const objs=[];const loader=new GLTFLoader();
function tex(p){const c=document.createElement('canvas');c.width=768;c.height=384;const x=c.getContext('2d');x.fillStyle='#'+p.color.toString(16).padStart(6,'0');x.fillRect(0,0,768,384);for(let i=0;i<240;i++){const v=40+Math.random()*140;x.fillStyle=`rgba(${v|0},${v*.82|0},${v*.6|0},${.05+Math.random()*.2})`;x.beginPath();x.ellipse(Math.random()*768,Math.random()*384,4+Math.random()*42,2+Math.random()*15,Math.random()*6.28,0,6.28);x.fill();}if(p.id==='earth'){for(let i=0;i<90;i++){x.fillStyle='rgba(45,130,70,.65)';x.beginPath();x.ellipse(Math.random()*768,30+Math.random()*320,5+Math.random()*32,3+Math.random()*16,Math.random()*6.28,0,6.28);x.fill();}}if(p.id==='jupiter'){x.strokeStyle='rgba(80,50,35,.25)';x.lineWidth=14;for(let y=20;y<380;y+=30){x.beginPath();x.moveTo(0,y);x.lineTo(768,y+(Math.random()-.5)*18);x.stroke();}x.fillStyle='rgba(160,70,45,.48)';x.beginPath();x.ellipse(540,195,58,22,0,0,6.28);x.fill();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function orbitLine(r){const g=new THREE.RingGeometry(r-.007,r+.007,256);g.rotateX(-Math.PI/2);root.add(new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x71809a,transparent:true,opacity:.22,side:THREE.DoubleSide})));}
function create(p){if(p.distance)orbitLine(p.distance);const pivot=new THREE.Group();pivot.rotation.y=Math.random()*6.28;root.add(pivot);const fallback=new THREE.Mesh(new THREE.SphereGeometry(p.size,64,40),new THREE.MeshStandardMaterial({map:tex(p),roughness:.9}));fallback.position.x=p.distance;fallback.userData.id=p.id;pivot.add(fallback);const o={...p,pivot,mesh:fallback,loaded:false};objs.push(o);if(p.id==='sun'){fallback.material=new THREE.MeshBasicMaterial({map:tex(p)});fallback.add(new THREE.Mesh(new THREE.SphereGeometry(p.size*1.18,36,24),new THREE.MeshBasicMaterial({color:0xffa02a,transparent:true,opacity:.15,side:THREE.BackSide})));}if(p.id==='saturn'){const ring=new THREE.Mesh(new THREE.RingGeometry(p.size*1.35,p.size*2.4,160),new THREE.MeshStandardMaterial({color:0xd0ba91,transparent:true,opacity:.78,side:THREE.DoubleSide}));ring.rotation.x=Math.PI/2.45;fallback.add(ring);}if(p.id==='earth'){o.moonPivot=new THREE.Group();fallback.add(o.moonPivot);o.moon=new THREE.Mesh(new THREE.SphereGeometry(.16,32,20),new THREE.MeshStandardMaterial({color:0xa9a8a2,roughness:1}));o.moon.position.x=1.45;o.moonPivot.add(o.moon);loader.load(BASE+'Moon.glb',g=>{const m=g.scene,b=new THREE.Box3().setFromObject(m),s=b.getSize(new THREE.Vector3()),mx=Math.max(s.x,s.y,s.z)||1;m.scale.setScalar(.32/mx);m.updateMatrixWorld(true);const c=new THREE.Box3().setFromObject(m).getCenter(new THREE.Vector3());m.position.sub(c);m.position.x=1.45;o.moonPivot.remove(o.moon);o.moonPivot.add(m);o.moon=m;},undefined,()=>{});}if(URLS[p.id])loader.load(BASE+URLS[p.id],g=>{const m=g.scene,b=new THREE.Box3().setFromObject(g.scene),s=b.getSize(new THREE.Vector3()),mx=Math.max(s.x,s.y,s.z)||1;m.scale.setScalar(p.size*2/mx);m.updateMatrixWorld(true);const c=new THREE.Box3().setFromObject(m).getCenter(new THREE.Vector3());m.position.sub(c);m.position.x=p.distance;m.rotation.z=p.id==='uranus'?1.71:0;m.userData.id=p.id;m.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});pivot.remove(fallback);pivot.add(m);o.mesh=m;o.loaded=true;},undefined,()=>{}));}
P.forEach(create);
const bg=new THREE.BufferGeometry(),bp=[];for(let i=0;i<2200;i++){const r=12.2+Math.random()*2.1,a=Math.random()*6.283;bp.push(Math.cos(a)*r,(Math.random()-.5)*.9,Math.sin(a)*r);}bg.setAttribute('position',new THREE.Float32BufferAttribute(bp,3));root.add(new THREE.Points(bg,new THREE.PointsMaterial({color:0xb7aa90,size:.05,transparent:true,opacity:.8})));
let selected=objs[0],paused=false,timeIndex=2,shipMode=false;const $=id=>document.getElementById(id);const tm=[{label:'暂停',rate:0},{label:'1 天 / 秒',rate:1},{label:'1 月 / 秒',rate:30},{label:'1 年 / 秒',rate:365.25},{label:'10 年 / 秒',rate:3652.5},{label:'100 年 / 秒',rate:36525}];
function show(p){selected=p;$('planetNo').textContent=String(P.findIndex(x=>x.id===p.id)+1).padStart(2,'0');$('latin').textContent=p.latin;$('name').textContent=p.name;$('tagline').textContent=p.tag;$('desc').textContent=p.desc;$('facts').innerHTML=p.facts.map(f=>`<div class="fact"><b>${f[1]}</b><span>${f[0]}</span></div>`).join('');document.querySelectorAll('.planet-list button').forEach(b=>b.classList.toggle('active',b.dataset.id===p.id));}
function select(p){if(!p||!p.mesh)return;show(p);const v=p.mesh.getWorldPosition(new THREE.Vector3());if(shipMode){ship.position.copy(v).add(new THREE.Vector3(0,0,Math.max(4,p.size*7)));return;}controls.target.copy(v);camera.position.copy(v).add(new THREE.Vector3(Math.max(4,p.size*5+3),Math.max(3,p.size*2+2),Math.max(5,p.size*7+4)));controls.update();}
const list=$('planetList');P.forEach((p,i)=>{const b=document.createElement('button');b.dataset.id=p.id;b.innerHTML=`<em>${String(i+1).padStart(2,'0')}</em>${p.name}`;b.onclick=()=>select(p);list.appendChild(b)});show(selected);
$('pauseBtn').onclick=()=>{paused=!paused;if(!paused&&timeIndex===0)timeIndex=2;$('speed').value=paused?0:timeIndex;$('speedValue').textContent=tm[paused?0:timeIndex].label;$('pauseBtn').textContent=paused?'▶ 继续':'Ⅱ 暂停'};
$('focusBtn').onclick=()=>select(selected);$('speed').oninput=e=>{timeIndex=+e.target.value;paused=timeIndex===0;$('speedValue').textContent=tm[timeIndex].label;$('pauseBtn').textContent=paused?'▶ 继续':'Ⅱ 暂停'};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('speed').value=b.dataset.speed;$('speed').dispatchEvent(new Event('input'))});
const ship=new THREE.Group();const shBody=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.58,4,8),new THREE.MeshStandardMaterial({color:0xe5eaf2,metalness:.65,roughness:.3}));shBody.rotation.z=-Math.PI/2;ship.add(shBody);const shWing=new THREE.Mesh(new THREE.BoxGeometry(.92,.035,.3),new THREE.MeshStandardMaterial({color:0x6e83a6,metalness:.55,roughness:.35}));shWing.position.x=-.08;ship.add(shWing);ship.add(new THREE.PointLight(0x8daeff,2,3));scene.add(ship);ship.visible=false;
const keys=new Set();let velocity=new THREE.Vector3(),yaw=0,pitch=0,mouseLocked=false;const moveSpeed=3;
function toggleShip(){shipMode=!shipMode;document.body.classList.toggle('ship-active',shipMode);ship.visible=shipMode;controls.enabled=!shipMode;if(shipMode){ship.position.copy(camera.position);ship.quaternion.copy(camera.quaternion);const eul=new THREE.Euler().setFromQuaternion(ship.quaternion,'YXZ');yaw=eul.y;pitch=eul.x;velocity.set(0,0,0);$('shipBtn').textContent='✕ EXIT SPACE · 退出飞船';$('status').textContent='SHIP MODE READY';}else{$('shipBtn').textContent='🚀 ENTER SPACE · 飞船模式';if(document.pointerLockElement===renderer.domElement)document.exitPointerLock();camera.position.copy(ship.position).add(new THREE.Vector3(2,1,4));camera.lookAt(ship.position);controls.target.copy(ship.position);controls.enabled=true;controls.update();}}
$('shipBtn').onclick=toggleShip;
addEventListener('keydown',e=>{if(e.code==='KeyF'){toggleShip();return;}keys.add(e.code);if(shipMode&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});addEventListener('keyup',e=>keys.delete(e.code));
renderer.domElement.addEventListener('click',()=>{if(shipMode&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock?.();});document.addEventListener('pointerlockchange',()=>{mouseLocked=document.pointerLockElement===renderer.domElement;});document.addEventListener('mousemove',e=>{if(!shipMode||!mouseLocked)return;yaw-=e.movementX*.0025;pitch-=e.movementY*.0025;pitch=Math.max(-1.45,Math.min(1.45,pitch));});
function fly(dt){if(!shipMode)return;ship.rotation.order='YXZ';ship.rotation.y=yaw;ship.rotation.x=pitch;const forward=new THREE.Vector3(0,0,-1).applyQuaternion(ship.quaternion);const right=new THREE.Vector3(1,0,0).applyQuaternion(ship.quaternion);const up=new THREE.Vector3(0,1,0);const accel=new THREE.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))accel.add(forward);if(keys.has('KeyS')||keys.has('ArrowDown'))accel.sub(forward);if(keys.has('KeyA')||keys.has('ArrowLeft'))accel.sub(right);if(keys.has('KeyD')||keys.has('ArrowRight'))accel.add(right);if(keys.has('KeyQ'))accel.add(up);if(keys.has('KeyE'))accel.sub(up);if(accel.lengthSq())accel.normalize();const boost=keys.has('ShiftLeft')||keys.has('ShiftRight')?4:1;if(keys.has('Space'))velocity.multiplyScalar(Math.pow(.01,dt));else velocity.addScaledVector(accel,dt*moveSpeed*boost);velocity.clampLength(0,moveSpeed*boost*4);ship.position.addScaledVector(velocity,dt);$('shipSpeed').textContent=velocity.length().toFixed(2)+' u/s';}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),r=tm[timeIndex].rate;if(!paused){objs.forEach(o=>{if(o.mesh)o.mesh.rotation.y+=o.rot*dt*(.7+r/365.25);if(o.pivot)o.pivot.rotation.y+=o.orbit*dt*(.16+r/5000);if(o.moonPivot)o.moonPivot.rotation.y+=1.9*dt*(.35+r/365.25);});}fly(dt);controls.update();renderer.render(scene,camera);$('status').textContent=shipMode?'SHIP MODE · WASD / QE / MOUSE':`LIVE · ${P.length} WORLDS · GLB MODELS · 3D`;}animate();
