import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const data=[
{id:'sun',name:'太阳',latin:'SUN',tag:'太阳系中心',color:0xffb52e,size:2.55,distance:0,orbit:0,rot:.08,desc:'太阳是一颗G型主序星，质量约占太阳系总质量的99.86%。',facts:[['类型','G型主序星'],['直径','1,392,700 km'],['温度','约 5,500°C']]},
{id:'mercury',name:'水星',latin:'MERCURY',tag:'最靠近太阳的行星',color:0x9c9990,size:.34,distance:4.2,orbit:1.60,rot:.025,desc:'水星是太阳系最小的行星，也是公转速度最快的行星。',facts:[['类型','类地行星'],['直径','4,879 km'],['公转','87.97 天']]},
{id:'venus',name:'金星',latin:'VENUS',tag:'炽热的姐妹行星',color:0xd5a16a,size:.56,distance:6.2,orbit:1.18,rot:-.018,desc:'金星拥有浓厚大气层，是太阳系行星表面最热的世界。',facts:[['类型','类地行星'],['直径','12,104 km'],['公转','224.7 天']]},
{id:'earth',name:'地球',latin:'EARTH',tag:'我们的蓝色家园',color:0x347cc7,size:.59,distance:8.5,orbit:1,rot:.65,tilt:.41,desc:'地球是目前已知唯一存在生命的行星，海洋覆盖约71%的表面。',facts:[['类型','类地行星'],['直径','12,742 km'],['公转','365.25 天']]},
{id:'mars',name:'火星',latin:'MARS',tag:'红色星球',color:0xb84f35,size:.44,distance:11,orbit:.80,rot:.62,desc:'火星因氧化铁而呈红色，拥有奥林匹斯山和水手峡谷。',facts:[['类型','类地行星'],['直径','6,779 km'],['公转','687 天']]},
{id:'jupiter',name:'木星',latin:'JUPITER',tag:'太阳系最大的行星',color:0xc48b60,size:1.38,distance:15,orbit:.43,rot:1.35,desc:'木星是太阳系最大的行星，大红斑是一场巨大的长期风暴。',facts:[['类型','气态巨行星'],['直径','139,820 km'],['公转','11.86 年']]},
{id:'saturn',name:'土星',latin:'SATURN',tag:'拥有壮丽光环',color:0xd8b77e,size:1.15,distance:20,orbit:.32,rot:1.12,desc:'土星以由冰、岩石和尘埃组成的壮丽光环闻名。',facts:[['类型','气态巨行星'],['直径','116,460 km'],['公转','29.45 年']]},
{id:'uranus',name:'天王星',latin:'URANUS',tag:'横躺着自转的冰巨星',color:0x79cbd1,size:.78,distance:24.5,orbit:.23,rot:-.72,tilt:1.71,desc:'天王星自转轴倾角约98°，几乎是“躺着”绕太阳运动。',facts:[['类型','冰巨行星'],['直径','50,724 km'],['公转','84 年']]},
{id:'neptune',name:'海王星',latin:'NEPTUNE',tag:'遥远而湛蓝的冰巨星',color:0x356bd2,size:.76,distance:29,orbit:.18,rot:.88,desc:'海王星是八大行星中最外侧的一颗，拥有极强的行星风。',facts:[['类型','冰巨行星'],['直径','49,244 km'],['公转','164.8 年']]},
{id:'pluto',name:'冥王星',latin:'PLUTO',tag:'柯伊伯带矮行星',color:0xa99c92,size:.25,distance:34,orbit:.12,rot:.35,desc:'冥王星位于遥远的柯伊伯带，是著名的矮行星。',facts:[['类型','矮行星'],['直径','2,377 km'],['公转','248 年']]}
];

const MODEL_BASE='https://raw.githubusercontent.com/Vivekkk-1/Galaticvisions/master/GLB/';
const modelUrls={sun:MODEL_BASE+'Sun.glb',mercury:MODEL_BASE+'Mercury.glb',venus:MODEL_BASE+'Venus.glb',mars:MODEL_BASE+'Mars.glb',jupiter:MODEL_BASE+'Jupiter.glb',saturn:MODEL_BASE+'Saturn.glb',uranus:MODEL_BASE+'Uranus.glb',neptune:MODEL_BASE+'Neptune.glb',pluto:MODEL_BASE+'Pluto_1_2374.glb'};
const moonUrl=MODEL_BASE+'Moon.glb';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x01030a);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.05,1000);camera.position.set(30,20,38);
const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#stage'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=.7;controls.maxDistance=130;controls.target.set(8,0,0);
scene.add(new THREE.AmbientLight(0x6d7890,.22));scene.add(new THREE.PointLight(0xffd08a,420,180,1.4));
function stars(){const g=new THREE.BufferGeometry(),p=[];for(let i=0;i<9000;i++){const r=100+Math.random()*350,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);p.push(r*Math.sin(b)*Math.cos(a),r*Math.cos(b),r*Math.sin(b)*Math.sin(a));}g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xffffff,size:.12,sizeAttenuation:true,transparent:true,opacity:.8})));}stars();
const root=new THREE.Group();scene.add(root);const objects=[];const loader=new GLTFLoader();
function orbitLine(r){const g=new THREE.RingGeometry(r-.006,r+.006,256);g.rotateX(-Math.PI/2);root.add(new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x6c7890,transparent:true,opacity:.25,side:THREE.DoubleSide})));}
function texture(d){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#'+d.color.toString(16).padStart(6,'0');x.fillRect(0,0,1024,512);for(let i=0;i<400;i++){const v=30+Math.random()*150;x.fillStyle=`rgba(${v|0},${(v*.85)|0},${(v*.6)|0},${.05+Math.random()*.18})`;x.beginPath();x.ellipse(Math.random()*1024,Math.random()*512,5+Math.random()*55,2+Math.random()*20,Math.random()*6.28,0,6.28);x.fill();}if(d.id==='earth'){for(let i=0;i<100;i++){x.fillStyle='rgba(45,125,65,.7)';x.beginPath();x.ellipse(Math.random()*1024,50+Math.random()*410,5+Math.random()*40,3+Math.random()*20,Math.random()*6.28,0,6.28);x.fill();}}if(d.id==='jupiter'){x.strokeStyle='rgba(75,45,30,.28)';x.lineWidth=16;for(let y=25;y<490;y+=38){x.beginPath();x.moveTo(0,y);x.lineTo(1024,y+Math.random()*22-11);x.stroke();}x.fillStyle='rgba(145,65,40,.5)';x.beginPath();x.ellipse(720,270,78,32,0,0,6.28);x.fill();}return new THREE.CanvasTexture(c);}
function fallback(d){const mesh=new THREE.Mesh(new THREE.SphereGeometry(d.size,64,40),new THREE.MeshStandardMaterial({map:texture(d),roughness:.9}));mesh.position.x=d.distance;mesh.rotation.z=d.tilt||0;return mesh;}
function makeRing(d,mesh){const ring=new THREE.Mesh(new THREE.RingGeometry(d.size*1.35,d.size*2.35,160),new THREE.MeshStandardMaterial({color:0xd0ba91,transparent:true,opacity:.78,side:THREE.DoubleSide,roughness:1}));ring.rotation.x=Math.PI/2.45;mesh.add(ring);}
function normalizeModel(model,d){const box=new THREE.Box3().setFromObject(model);const size=box.getSize(new THREE.Vector3());const max=Math.max(size.x,size.y,size.z)||1;model.scale.setScalar((d.size*2)/max);const box2=new THREE.Box3().setFromObject(model);const center=box2.getCenter(new THREE.Vector3());model.position.sub(center);model.position.x+=d.distance;model.rotation.z=d.tilt||0;model.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});}
function create(d){if(d.distance)orbitLine(d.distance);const pivot=new THREE.Group();pivot.rotation.y=Math.random()*Math.PI*2;root.add(pivot);const mesh=fallback(d);mesh.userData.id=d.id;pivot.add(mesh);const obj={...d,pivot,mesh,loaded:false};objects.push(obj);
if(d.id==='sun'){mesh.material=new THREE.MeshBasicMaterial({map:texture(d)});mesh.add(new THREE.Mesh(new THREE.SphereGeometry(d.size*1.18,40,28),new THREE.MeshBasicMaterial({color:0xff9b28,transparent:true,opacity:.16,side:THREE.BackSide})))}
if(d.id==='saturn')makeRing(d,mesh);
if(d.id==='earth'){const moonPivot=new THREE.Group();mesh.add(moonPivot);const moon=new THREE.Mesh(new THREE.SphereGeometry(.16,32,20),new THREE.MeshStandardMaterial({color:0xa9a8a2,roughness:1}));moon.position.x=1.45;moon.userData.id='moon';moonPivot.add(moon);obj.moonPivot=moonPivot;obj.moon=moon;loader.load(moonUrl,g=>{const m=g.scene;const box=new THREE.Box3().setFromObject(m);const s=box.getSize(new THREE.Vector3());m.scale.setScalar(.32/(Math.max(s.x,s.y,s.z)||1));const c=new THREE.Box3().setFromObject(m).getCenter(new THREE.Vector3());m.position.sub(c);m.position.x=1.45;moonPivot.remove(moon);moonPivot.add(m);obj.moon=m;})}
const url=modelUrls[d.id];if(url){loader.load(url,g=>{const model=g.scene;normalizeModel(model,d);pivot.remove(mesh);pivot.add(model);obj.mesh=model;obj.loaded=true;model.userData.id=d.id;},undefined,()=>{});}return obj;}
data.forEach(create);
const ag=new THREE.BufferGeometry(),ap=[];for(let i=0;i<1800;i++){const r=12.2+Math.random()*2.1,a=Math.random()*Math.PI*2;ap.push(Math.cos(a)*r,(Math.random()-.5)*.9,Math.sin(a)*r);}ag.setAttribute('position',new THREE.Float32BufferAttribute(ap,3));root.add(new THREE.Points(ag,new THREE.PointsMaterial({color:0xb7aa90,size:.05,transparent:true,opacity:.75})));
let selected=objects[0],paused=false,speed=1;const $=id=>document.getElementById(id),ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function show(d){selected=d;$('planetNo').textContent=String(Math.max(0,data.findIndex(x=>x.id===d.id)+1)).padStart(2,'0');$('latin').textContent=d.latin;$('name').textContent=d.name;$('tagline').textContent=d.tag;$('desc').textContent=d.desc;$('facts').innerHTML=d.facts.map(f=>`<div class="fact"><b>${f[1]}</b><span>${f[0]}</span></div>`).join('');document.querySelectorAll('.planet-list button').forEach(b=>b.classList.toggle('active',b.dataset.id===d.id));}
const list=$('planetList');data.forEach((d,i)=>{const b=document.createElement('button');b.dataset.id=d.id;b.innerHTML=`<em>${String(i+1).padStart(2,'0')}</em>${d.name}`;b.onclick=()=>select(d);list.appendChild(b)});show(selected);
function select(d){if(!d)return;show(d);const target=d.mesh||d.pivot;if(!target)return;const p=target.getWorldPosition(new THREE.Vector3());const offset=new THREE.Vector3(Math.max(4,d.size*5+3),Math.max(3,d.size*2+2),Math.max(5,d.size*6+5));controls.target.copy(p);camera.position.copy(p).add(offset);controls.update();}
$('pauseBtn').onclick=()=>{paused=!paused;$('pauseBtn').textContent=paused?'▶ 继续':'Ⅱ 暂停'};$('focusBtn').onclick=()=>select(selected);$('speed').oninput=e=>{speed=+e.target.value;$('speedValue').textContent=speed.toFixed(1)+'×';paused=speed===0};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('speed').value=b.dataset.speed;$('speed').dispatchEvent(new Event('input'))});
renderer.domElement.addEventListener('pointerdown',e=>{mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(objects.map(o=>o.mesh),true)[0];if(hit){let n=hit.object;while(n&&!n.userData.id)n=n.parent;const d=objects.find(o=>o.id===n?.userData.id);if(d)select(d)}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(!paused){objects.forEach(o=>{if(o.mesh)o.mesh.rotation.y+=o.rot*dt*speed;if(o.pivot)o.pivot.rotation.y+=o.orbit*dt*.35*speed;if(o.moonPivot)o.moonPivot.rotation.y+=1.9*dt*speed});}controls.update();renderer.render(scene,camera);$('status').textContent=paused?'SIMULATION PAUSED':`LIVE · ${data.length} WORLDS · GLB MODELS · 3D`;}animate();