import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const $=s=>document.querySelector(s),MAX=18*1024*1024;
const data={
 lion:{no:'01',name:'非洲狮',latin:'PANTHERA LEO',tagline:'草原上的群居大型猫科动物。',facts:[['栖息地','非洲草原'],['体重','约 120–250 kg'],['最高速度','约 80 km/h']],desc:'狮子是现存最大的猫科动物之一。它们通常以群体形式生活，雄狮醒目的鬃毛是其最具代表性的特征之一。',speech:'你好，欢迎来到三维野生动物馆。现在看到的是非洲狮。狮子通常生活在非洲草原和稀树草原地区，是少数具有稳定群居社会结构的大型猫科动物。',url:'https://raw.githubusercontent.com/code4fukui/vr-cats/main/lion.glb'},
 tiger:{no:'02',name:'孟加拉虎',latin:'PANTHERA TIGRIS TIGRIS',tagline:'独居、敏捷而强大的大型猫科捕食者。',facts:[['栖息地','森林与草原'],['体重','约 100–260 kg'],['最高速度','短距离约 60 km/h']],desc:'老虎是现存体型最大的猫科动物之一。橙色毛皮上的深色条纹能帮助它融入林下斑驳的光影环境。',speech:'你好，现在来到老虎展区。老虎是体型最大的现存猫科动物之一，通常以独居方式活动，具有非常出色的力量、感知能力和短距离爆发力。',url:'./models/tiger.glb'}
};
const st={lion:{loaded:0,total:0,phase:'waiting'},tiger:{loaded:0,total:0,phase:'waiting'}},cache=new Map(),pending=new Map(),loader=new GLTFLoader();
let scene,camera,renderer,controls,current=null,mixer=null,clips=[],active='lion';const clock=new THREE.Clock();
const patterns={idle:/idle|stand|rest|breath|wait/i,walk:/walk|walking|stroll|run|running|locomotion/i,roar:/roar|growl|attack|call|cry|bite/i};
const MB=v=>v?(v/1048576).toFixed(1)+' MB':'—';
function textStage(a,b){$('#loadingStage').textContent=a;$('#loadingMessage').textContent=b}
function label(s){if(s.phase==='done')return'完成';if(s.phase==='parsing')return'解析中';if(s.phase==='downloading'&&s.total)return Math.min(99,Math.round(s.loaded/s.total*100))+'%';return s.phase==='downloading'?'下载中':'等待'}
function refresh(){const vals=[st.lion,st.tiger],total=vals.reduce((n,s)=>n+s.total,0),loaded=vals.reduce((n,s)=>n+s.loaded,0);let pct=total?Math.min(99,Math.round(loaded/total*100)):Math.round(vals.filter(s=>s.phase==='done').length/2*100);if(vals.every(s=>s.phase==='done'))pct=100;$('#progressFill').style.width=pct+'%';$('#progressPercent').textContent=pct+'%';$('#progressSize').textContent=total?MB(loaded)+' / '+MB(total):'读取模型大小…';$('#lionProgress').textContent=label(st.lion);$('#tigerProgress').textContent=label(st.tiger)}
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x080a0b);scene.fog=new THREE.FogExp2(0x080a0b,.025);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,2.4,8);renderer=new THREE.WebGLRenderer({canvas:$('#stage'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=11;controls.target.set(0,1.2,0);scene.add(new THREE.HemisphereLight(0xfff5e2,0x101820,2.5));const key=new THREE.DirectionalLight(0xffd99c,4);key.position.set(4,7,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x5b9dff,2);rim.position.set(-5,3,-4);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x17130d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);scene.add(new THREE.GridHelper(12,24,0x342b1e,0x161616));animate()}
async function fetchBytes(kind){const s=st[kind];if(s.phase==='done')return null;s.phase='downloading';s.loaded=0;s.total=0;textStage('正在下载 '+data[kind].name,data[kind].name+'：读取真实 GLB 文件…');refresh();const r=await fetch(data[kind].url,{cache:'force-cache'});if(!r.ok)throw Error('HTTP '+r.status);const len=Number(r.headers.get('content-length'))||0;s.total=len;if(len&&len>MAX)throw Error(data[kind].name+' 模型超过 18 MB 上限');if(!r.body){const b=await r.arrayBuffer();s.loaded=b.byteLength;if(!s.total)s.total=s.loaded;if(s.loaded>MAX)throw Error(data[kind].name+' 模型超过 18 MB 上限');refresh();return b}const rd=r.body.getReader(),chunks=[];while(true){const x=await rd.read();if(x.done)break;chunks.push(x.value);s.loaded+=x.value.byteLength;if(s.loaded>MAX){try{await rd.cancel()}catch{}throw Error(data[kind].name+' 模型超过 18 MB 上限')}refresh()}const b=new Uint8Array(s.loaded);let off=0;for(const c of chunks){b.set(c,off);off+=c.byteLength}if(!s.total)s.total=s.loaded;return b.buffer}
function parse(kind,b){st[kind].phase='parsing';textStage('正在解析 '+data[kind].name,data[kind].name+'：下载完成，正在建立网格、材质与骨骼…');refresh();return new Promise((ok,no)=>loader.parse(b,'',ok,no))}
async function load(kind){if(cache.has(kind))return cache.get(kind);if(pending.has(kind))return pending.get(kind);const p=(async()=>{const b=await fetchBytes(kind),g=await parse(kind,b),e={gltf:g};cache.set(kind,e);st[kind].phase='done';st[kind].loaded=st[kind].total;refresh();return e})();pending.set(kind,p);try{return await p}finally{pending.delete(kind)}}
function prepare(m,kind){if(m.userData.prepared)return;const box=new THREE.Box3().setFromObject(m),size=box.getSize(new THREE.Vector3()).length(),target=kind==='tiger'?4.9:4.2;if(size)m.scale.multiplyScalar(target/size);const b=new THREE.Box3().setFromObject(m),c=b.getCenter(new THREE.Vector3());m.position.x-=c.x;m.position.z-=c.z;m.position.y-=b.min.y;m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});m.userData.prepared=true}
function mixerFor(g){mixer=null;clips=[];if(!g.animations?.length)return;mixer=new THREE.AnimationMixer(g.scene);clips=g.animations;const map={};for(const k in patterns){const c=clips.find(x=>patterns[k].test(x.name));if(c)map[k]=mixer.clipAction(c)}mixer.map=map}
function action(mode){document.querySelectorAll('.action').forEach(b=>b.classList.toggle('active',b.dataset.action===mode));if(!mixer){$('#actionHint').textContent='这个 GLB 没有骨骼动作。';return}Object.values(mixer.map).forEach(a=>a.stop());const a=mixer.map[mode]||mixer.map.idle||mixer.clipAction(clips[0]);if(!a)return;a.reset().fadeIn(.25).play();a.setLoop(mode==='roar'?THREE.LoopOnce:THREE.LoopRepeat,mode==='roar'?1:Infinity);$('#actionHint').textContent=mixer.map[mode]?`原生 GLB 动作：${a.getClip().name}`:'当前 GLB 没有该动作，使用可用动作近似。'}
function show(kind,e){if(current)scene.remove(current);if(mixer)mixer.stopAllAction();current=e.gltf.scene;prepare(current,kind);scene.add(current);mixerFor(e.gltf);$('#modelStatus').textContent=data[kind].name+' 已就绪';action('idle')}
function info(k){const d=data[k];$('#animalNo').textContent=d.no;$('#name').textContent=d.name;$('#latin').textContent=d.latin;$('#tagline').textContent=d.tagline;$('#facts').innerHTML=d.facts.map(([a,b])=>`<div class="fact"><b>${a}</b><span>${b}</span></div>`).join('');$('#desc').textContent=d.desc}
function select(k){active=k;info(k);speechSynthesis.cancel();document.querySelectorAll('.animal').forEach(b=>b.classList.toggle('active',b.dataset.animal===k));const e=cache.get(k);if(e)show(k,e)}
function animate(){requestAnimationFrame(animate);if(mixer)mixer.update(clock.getDelta());controls?.update();renderer?.render(scene,camera)}
$('.animals').addEventListener('click',e=>{const b=e.target.closest('.animal');if(b)select(b.dataset.animal)});$('#actions').addEventListener('click',e=>{const b=e.target.closest('.action');if(b)action(b.dataset.action)});$('#voiceBtn').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(data[active].speech);u.lang='zh-CN';u.rate=.92;speechSynthesis.speak(u)};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
setup();info('lion');(async()=>{textStage('正在启动 3D 展馆','正在同时预加载狮子和老虎，下载完成后立即缓存。');try{const [l,t]=await Promise.all([load('lion'),load('tiger')]);show('lion',l);$('#progressFill').style.width='100%';$('#progressPercent').textContent='100%';$('#loadingMessage').textContent='两个模型已解析完成，可瞬间切换。';setTimeout(()=>$('#loading').classList.add('hide'),350)}catch(e){console.error(e);textStage('模型加载失败',e.message||'请检查网络并刷新');}})();
