import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
const data={lion:{no:'01',name:'非洲狮',latin:'PANTHERA LEO',tagline:'草原上的群居大型猫科动物。',facts:[['栖息地','非洲草原'],['体重','约 120–250 kg'],['最高速度','约 80 km/h']],desc:'狮子是现存最大的猫科动物之一。它们通常以群体形式生活，雄狮醒目的鬃毛是其最具代表性的特征之一。',speech:'你好，欢迎来到三维野生动物馆。现在看到的是非洲狮。狮子通常生活在非洲的草原和稀树草原地区，是少数具有稳定群居社会结构的大型猫科动物。'},tiger:{no:'02',name:'孟加拉虎',latin:'PANTHERA TIGRIS TIGRIS',tagline:'独居、敏捷而强大的大型猫科捕食者。',facts:[['栖息地','森林与草原'],['体重','约 100–260 kg'],['最高速度','短距离约 60 km/h']],desc:'老虎是现存体型最大的猫科动物。它们的条纹不仅具有鲜明外观，也能在植被与光影中帮助隐藏身体轮廓。',speech:'你好，现在来到老虎展区。老虎是体型最大的现存猫科动物之一，通常以独居方式活动，具有非常出色的力量、感知能力和短距离爆发力。'}};
let scene,camera,renderer,controls,clock=new THREE.Clock(),mixer,current,active='lion';const loader=new GLTFLoader();const $=s=>document.querySelector(s);
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x080a0b);scene.fog=new THREE.FogExp2(0x080a0b,.025);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,2.4,8);renderer=new THREE.WebGLRenderer({canvas:$('#stage'),antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=11;controls.target.set(0,1.2,0);scene.add(new THREE.HemisphereLight(0xfff5e2,0x101820,2.5));const key=new THREE.DirectionalLight(0xffd99c,4);key.position.set(4,7,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x5b9dff,2);rim.position.set(-5,3,-4);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x17130d,roughness:1,metalness:0}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(12,24,0x342b1e,0x161616);grid.position.y=.01;scene.add(grid);animate();}
function fallback(kind){const g=new THREE.Group();let body;if(kind==='lion'){body=new THREE.Mesh(new THREE.SphereGeometry(1.05,48,32),new THREE.MeshStandardMaterial({color:0xb77a32,roughness:.8}));body.scale.set(1.5,.9,.9);const head=new THREE.Mesh(new THREE.SphereGeometry(.72,32,24),new THREE.MeshStandardMaterial({color:0xc58a42}));head.position.set(1.25,.25,0);g.add(body,head);const mane=new THREE.Mesh(new THREE.TorusGeometry(.78,.18,16,32),new THREE.MeshStandardMaterial({color:0x5a3218}));mane.position.set(1.2,.25,0);mane.rotation.y=Math.PI/2;g.add(mane)}else{body=new THREE.Mesh(new THREE.CapsuleGeometry(.7,2.1,12,32),new THREE.MeshStandardMaterial({color:0xe48a25,roughness:.75}));body.rotation.z=Math.PI/2;const head=new THREE.Mesh(new THREE.SphereGeometry(.62,32,24),new THREE.MeshStandardMaterial({color:0xe69a3b}));head.position.set(1.25,.15,0);g.add(body,head);for(let i=-3;i<=3;i++){const s=new THREE.Mesh(new THREE.BoxGeometry(.12,1.2,.95),new THREE.MeshStandardMaterial({color:0x26180f}));s.position.x=i*.38;g.add(s)}}g.position.y=1;return g}
async function loadAnimal(kind){$('#modelStatus').textContent='正在加载 '+data[kind].name;if(current){scene.remove(current);current=null}if(mixer)mixer=null;let model;try{if(kind==='lion'){const gltf=await loader.loadAsync('https://raw.githubusercontent.com/code4fukui/vr-cats/main/lion.glb');model=gltf.scene;mixer=new THREE.AnimationMixer(model);if(gltf.animations.length)mixer.clipAction(gltf.animations[0]).play()}else{throw new Error('使用内置 Tiger 展示模型')}}catch(e){model=fallback(kind)}const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()).length();if(size>0)model.scale.multiplyScalar(4.2/size);model.position.y=0;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(model);current=model;$('#loading').classList.add('hide');$('#modelStatus').textContent=data[kind].name+' 已就绪'}
function setInfo(kind){const d=data[kind];$('#animalNo').textContent=d.no;$('#name').textContent=d.name;$('#latin').textContent=d.latin;$('#tagline').textContent=d.tagline;$('#facts').innerHTML=d.facts.map(x=>`<div class="fact"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$('#desc').textContent=d.desc}
function select(kind){if(active===kind)return;active=kind;setInfo(kind);loadAnimal(kind);document.querySelectorAll('.animal').forEach(b=>b.classList.toggle('active',b.dataset.animal===kind));speechSynthesis.cancel()}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(mixer)mixer.update(dt);if(current&&!mixer)current.rotation.y+=dt*.16;controls.update();renderer.render(scene,camera)}
$('.animals').addEventListener('click',e=>{const b=e.target.closest('.animal');if(b)select(b.dataset.animal)});$('#voiceBtn').onclick=()=>{if(!('speechSynthesis'in window))return alert('当前浏览器不支持语音合成');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(data[active].speech);u.lang='zh-CN';u.rate=.92;speechSynthesis.speak(u)};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});setup();setInfo('lion');loadAnimal('lion');