import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
const data={lion:{no:'01',name:'非洲狮',latin:'PANTHERA LEO',tagline:'草原上的群居大型猫科动物。',facts:[['栖息地','非洲草原'],['体重','约 120–250 kg'],['最高速度','约 80 km/h']],desc:'狮子是现存最大的猫科动物之一。它们通常以群体形式生活，雄狮醒目的鬃毛是其最具代表性的特征之一。',speech:'你好，欢迎来到三维野生动物馆。现在看到的是非洲狮。狮子通常生活在非洲的草原和稀树草原地区，是少数具有稳定群居社会结构的大型猫科动物。',url:'https://raw.githubusercontent.com/code4fukui/vr-cats/main/lion.glb'},tiger:{no:'02',name:'孟加拉虎',latin:'PANTHERA TIGRIS TIGRIS',tagline:'独居、敏捷而强大的大型猫科捕食者。',facts:[['栖息地','森林与草原'],['体重','约 100–260 kg'],['最高速度','短距离约 60 km/h']],desc:'老虎是现存体型最大的猫科动物之一。橙色毛皮上的深色条纹能帮助它融入林下斑驳的光影环境。',speech:'你好，现在来到老虎展区。老虎是体型最大的现存猫科动物之一，通常以独居方式活动，具有非常出色的力量、感知能力和短距离爆发力。',url:'https://storage.googleapis.com/ar-answers-in-search-models/static/Tiger/model.glb'}};
let scene,camera,renderer,controls,clock=new THREE.Clock(),current=null,mixer=null,clips=[],active='lion',actionMode='idle',modelToken=0,actionClock=0;const loader=new GLTFLoader();const $=s=>document.querySelector(s);
const patterns={idle:/idle|stand|rest|breath/i,walk:/walk|walking|stroll|run/i,roar:/roar|growl|attack|call|cry/i};
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x080a0b);scene.fog=new THREE.FogExp2(0x080a0b,.025);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,2.4,8);renderer=new THREE.WebGLRenderer({canvas:$('#stage'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=11;controls.target.set(0,1.2,0);scene.add(new THREE.HemisphereLight(0xfff5e2,0x101820,2.5));const key=new THREE.DirectionalLight(0xffd99c,4);key.position.set(4,7,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x5b9dff,2);rim.position.set(-5,3,-4);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x17130d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(12,24,0x342b1e,0x161616);grid.position.y=.01;scene.add(grid);animate();}
function stopMixer(){if(mixer){mixer.stopAllAction();if(current)mixer.uncacheRoot(current);mixer=null;}clips=[];}
function setupClips(gltf){stopMixer();if(!gltf.animations?.length)return;mixer=new THREE.AnimationMixer(gltf.scene);clips=gltf.animations;const map={};for(const mode of Object.keys(patterns)){const clip=clips.find(c=>patterns[mode].test(c.name));if(clip)map[mode]=mixer.clipAction(clip);}mixer._map=map;}
function proceduralMode(dt){if(!current||mixer)return;actionClock+=dt;const t=actionClock;const baseY=Math.sin(t*1.5)*.012;if(actionMode==='idle'){current.position.y=baseY;current.rotation.z*=.92;}else if(actionMode==='walk'){current.position.y=baseY+Math.abs(Math.sin(t*7))*0.055;current.rotation.z=Math.sin(t*7)*.018;current.position.x=Math.sin(t*2.2)*.12;}else{current.position.y=baseY+Math.abs(Math.sin(t*8))*0.045;current.rotation.z=Math.sin(t*5)*.025;current.rotation.x=Math.sin(t*9)*.02;}}
function playMode(mode){if(!current)return;actionMode=mode;actionClock=0;document.querySelectorAll('.action').forEach(b=>b.classList.toggle('active',b.dataset.action===mode));if(mixer){Object.values(mixer._map||{}).forEach(a=>a.stop());const target=mixer._map?.[mode]||mixer._map?.idle||clips[0]&&mixer.clipAction(clips[0]);if(target){target.reset().fadeIn(.25).play();target.setLoop(mode==='roar'?THREE.LoopOnce:THREE.LoopRepeat,mode==='roar'?1:Infinity);$('#actionHint').textContent=mixer._map?.[mode]?'原生 GLB 动作：'+target.getClip().name:'当前 GLB 未提供该动作，使用可用动作近似。';return;}}$('#actionHint').textContent='当前 GLB 没有骨骼动作，使用轻量展示动画模拟 '+mode.toUpperCase()+'。';}
async function loadAnimal(kind){const token=++modelToken;active=kind;$('#modelStatus').textContent='正在加载 '+data[kind].name;$('#actionHint').textContent='读取 GLB…';if(current){scene.remove(current);current=null;}stopMixer();try{const gltf=await loader.loadAsync(data[kind].url);if(token!==modelToken)return;current=gltf.scene;const box=new THREE.Box3().setFromObject(current);const size=box.getSize(new THREE.Vector3()).length();if(size)current.scale.multiplyScalar(4.2/size);current.position.y=0;current.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(current);setupClips(gltf);$('#loading').classList.add('hide');$('#modelStatus').textContent=data[kind].name+' 已就绪';playMode('idle');}catch(e){console.error(e);$('#loading').classList.add('hide');$('#modelStatus').textContent=data[kind].name+' 加载失败';$('#actionHint').textContent='GLB 资源访问失败，请刷新页面重试。';}}
function setInfo(kind){const d=data[kind];$('#animalNo').textContent=d.no;$('#name').textContent=d.name;$('#latin').textContent=d.latin;$('#tagline').textContent=d.tagline;$('#facts').innerHTML=d.facts.map(x=>`<div class="fact"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$('#desc').textContent=d.desc;}
function select(kind){if(active===kind)return;setInfo(kind);speechSynthesis.cancel();document.querySelectorAll('.animal').forEach(b=>b.classList.toggle('active',b.dataset.animal===kind));loadAnimal(kind);}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(mixer)mixer.update(dt);proceduralMode(dt);controls.update();renderer.render(scene,camera);}
$('.animals').addEventListener('click',e=>{const b=e.target.closest('.animal');if(b)select(b.dataset.animal);});$('#actions').addEventListener('click',e=>{const b=e.target.closest('.action');if(b)playMode(b.dataset.action);});$('#voiceBtn').onclick=()=>{if(!('speechSynthesis'in window))return alert('当前浏览器不支持语音合成');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(data[active].speech);u.lang='zh-CN';u.rate=.92;speechSynthesis.speak(u);};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});setup();setInfo('lion');loadAnimal('lion');