import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const $=s=>document.querySelector(s);
const SPECIES={
 lion:{no:'01',name:'非洲狮',latin:'PANTHERA LEO',tagline:'草原上的群居大型猫科动物。',facts:[['栖息地','非洲草原'],['体重','约 120–250 kg'],['最高速度','约 80 km/h']],desc:'狮子是现存最大的猫科动物之一，通常以群体形式生活。雄狮醒目的鬃毛是其最有辨识度的特征之一。',speech:'你好，现在看到的是非洲狮。狮子通常生活在非洲草原和稀树草原地区，是少数具有稳定群居社会结构的大型猫科动物。',url:'https://raw.githubusercontent.com/code4fukui/vr-cats/main/lion.glb',target:4.2},
 tiger:{no:'02',name:'孟加拉虎',latin:'PANTHERA TIGRIS TIGRIS',tagline:'独居、敏捷而强大的大型猫科捕食者。',facts:[['栖息地','森林、草原与湿地'],['体重','约 100–260 kg'],['最高速度','短距离约 60 km/h']],desc:'老虎通常独居活动，橙色毛皮上的深色条纹可以帮助它融入林下斑驳的光影环境。',speech:'你好，现在看到的是孟加拉虎。老虎是现存体型最大的猫科动物之一，通常独居，拥有非常强的爆发力和出色的感知能力。',url:'./models/tiger.glb',target:4.9}
};
const state={lion:{loaded:0,total:0,phase:'waiting'},tiger:{loaded:0,total:0,phase:'waiting'}};
const cache=new Map();const pending=new Map();const loader=new GLTFLoader();
let scene,camera,renderer,controls,current=null,mixer=null,active='lion';const clock=new THREE.Clock();
const patterns={idle:/idle|stand|rest|breath|wait/i,walk:/walk|walking|stroll|run|running|locomotion|move/i,roar:/roar|growl|attack|call|cry|bite/i};
function mb(v){return v?(v/1048576).toFixed(1)+' MB':'—'}
function phase(s){if(s.phase==='done')return'完成';if(s.phase==='parsing')return'解析中';if(s.phase==='error')return'失败';return s.phase==='downloading'&&s.total?Math.min(100,Math.floor(Math.min(s.loaded,s.total)/s.total*100))+'%':'等待'}
function progress(){const a=state.lion,b=state.tiger,total=a.total+b.total,loaded=Math.min(a.loaded,a.total||a.loaded)+Math.min(b.loaded,b.total||b.loaded);let pct=total?Math.min(100,Math.floor(loaded/total*100)):Math.floor([a,b].filter(x=>x.phase==='done').length/2*100);if(a.phase==='done'&&b.phase==='done')pct=100;$('#progressFill').style.width=pct+'%';$('#progressPercent').textContent=pct+'%';$('#progressSize').textContent=total?`${mb(loaded)} / ${mb(total)}`:'读取模型大小…';$('#lionProgress').textContent=phase(a);$('#tigerProgress').textContent=phase(b)}
function stage(t,m){$('#loadingStage').textContent=t;$('#loadingMessage').textContent=m}
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x080a0b);scene.fog=new THREE.FogExp2(0x080a0b,.025);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,2.4,8);renderer=new THREE.WebGLRenderer({canvas:$('#stage'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=11;controls.target.set(0,1.2,0);scene.add(new THREE.HemisphereLight(0xfff5e2,0x101820,2.5));const key=new THREE.DirectionalLight(0xffd99c,4);key.position.set(4,7,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x5b9dff,2);rim.position.set(-5,3,-4);scene.add(rim);const ground=new THREE.Mesh(new THREE.CircleGeometry(7,64),new THREE.MeshStandardMaterial({color:0x17130d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(12,24,0x342b1e,0x161616);grid.position.y=.01;scene.add(grid);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate()}
async function getBuffer(kind){if(pending.has(kind))return pending.get(kind);const p=(async()=>{const s=state[kind],u=SPECIES[kind].url;s.phase='downloading';s.loaded=0;s.total=0;stage(`正在下载 ${SPECIES[kind].name}`,`${SPECIES[kind].name}：同源 GLB 读取中…`);progress();const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`${SPECIES[kind].name} HTTP ${r.status}`);s.total=Number(r.headers.get('content-length'))||0;const body=r.body;if(!body){const b=await r.arrayBuffer();s.loaded=b.byteLength;s.total=s.total||s.loaded;progress();return b}const rd=body.getReader(),chunks=[];while(true){const x=await rd.read();if(x.done)break;chunks.push(x.value);s.loaded+=x.value.byteLength;progress()}if(s.loaded!==s.total)s.total=s.loaded;s.loaded=s.total;const out=new Uint8Array(s.total);let off=0;for(const c of chunks){out.set(c,off);off+=c.byteLength}progress();return out.buffer})();pending.set(kind,p);try{return await p}finally{pending.delete(kind)}}
async function load(kind){if(cache.has(kind))return cache.get(kind);const buf=await getBuffer(kind);state[kind].phase='parsing';stage(`正在解析 ${SPECIES[kind].name}`,`${SPECIES[kind].name}：建立网格、材质与骨骼…`);progress();const gltf=await new Promise((res,rej)=>loader.parse(buf,'',res,rej));cache.set(kind,gltf);state[kind].phase='done';state[kind].loaded=state[kind].total;progress();return gltf}
function prepare(m,kind){const box=new THREE.Box3().setFromObject(m),size=box.getSize(new THREE.Vector3()).length();if(size)m.scale.multiplyScalar(SPECIES[kind].target/size);const b=new THREE.Box3().setFromObject(m),c=b.getCenter(new THREE.Vector3());m.position.set(-c.x,-b.min.y,-c.z);m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}})}
function buildActions(gltf){mixer=null;if(!gltf.animations?.length)return;mixer=new THREE.AnimationMixer(gltf.scene);const map={};for(const c of gltf.animations){const n=c.name.toLowerCase();if(!map.idle&&patterns.idle.test(n))map.idle=mixer.clipAction(c);if(!map.walk&&patterns.walk.test(n))map.walk=mixer.clipAction(c);if(!map.roar&&patterns.roar.test(n))map.roar=mixer.clipAction(c)}if(!map.idle)map.idle=mixer.clipAction(gltf.animations[0]);mixer.map=map}
function play(mode){document.querySelectorAll('.action').forEach(b=>b.classList.toggle('active',b.dataset.action===mode));if(!mixer){$('#actionHint').textContent='这个 GLB 没有骨骼动作。';return}Object.values(mixer.map).forEach(a=>a.stop());const a=mixer.map[mode]||mixer.map.idle;if(!a)return;a.reset().fadeIn(.2).play();a.setLoop(mode==='roar'?THREE.LoopOnce:THREE.LoopRepeat,mode==='roar'?1:Infinity);$('#actionHint').textContent=mixer.map[mode]?`原生 GLB 动作：${a.getClip().name}`:'当前 GLB 没有该动作，使用可用动作。'}
function show(kind,gltf){if(current)scene.remove(current);if(mixer)mixer.stopAllAction();current=gltf.scene;prepare(current,kind);scene.add(current);buildActions(gltf);$('#modelStatus').textContent=`${SPECIES[kind].name} 已就绪`;play('idle')}
function info(kind){const d=SPECIES[kind];$('#animalNo').textContent=d.no;$('#name').textContent=d.name;$('#latin').textContent=d.latin;$('#tagline').textContent=d.tagline;$('#facts').innerHTML=d.facts.map(([a,b])=>`<div class="fact"><b>${a}</b><span>${b}</span></div>`).join('');$('#desc').textContent=d.desc}
function select(kind){active=kind;info(kind);speechSynthesis.cancel();document.querySelectorAll('.animal').forEach(b=>b.classList.toggle('active',b.dataset.animal===kind));const gltf=cache.get(kind);if(gltf)show(kind,gltf)}
function animate(){requestAnimationFrame(animate);if(mixer)mixer.update(clock.getDelta());controls?.update();renderer?.render(scene,camera)}
$('.animals').addEventListener('click',e=>{const b=e.target.closest('.animal');if(b)select(b.dataset.animal)});$('#actions').addEventListener('click',e=>{const b=e.target.closest('.action');if(b)play(b.dataset.action)});$('#voiceBtn').addEventListener('click',()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(SPECIES[active].speech);u.lang='zh-CN';u.rate=.92;speechSynthesis.speak(u)});
setup();info('lion');
(async()=>{stage('正在预加载动物模型','狮子和老虎都会在进入页面前完成下载与解析。');try{const [lion,tiger]=await Promise.all([load('lion'),load('tiger')]);show('lion',lion);$('#loadingMessage').textContent='狮子与老虎均已加载完成，可以瞬间切换。';state.lion.phase='done';state.tiger.phase='done';progress();setTimeout(()=>$('#loading').classList.add('hide'),350)}catch(e){console.error(e);state.lion.phase=state.lion.phase==='done'?'done':'error';if(state.tiger.phase!=='done')state.tiger.phase='error';progress();stage('模型加载失败',e.message||'请检查模型文件并刷新页面。')}})();
